name: Code Quality

on:
  push:
    paths:
      - "**.py"

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - name: Flake8 action
        uses: suo/flake8-github-action@v1
