name: udacity_project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIA2J3CN2DS5RW2GBDH
        aws-secret-access-key: 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
        aws-region: us-east-1
        
    - name: setup-dvc
      uses: iterative/setup-dvc@v1
    
    - name: run dvc 
      run: dvc pull

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
        

