name: udacity_project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIA2J3CN2DS5RW2GBDH
        aws-secret-access-key: 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
        aws-region: us-east-2